name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly, v0.11.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.15.0
      - name: zig build
        run: |
          cd zig
          zig build install
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}
      - name: Run Tests
        run: |
          nvim --version
          [ ! -d tests ] && exit 0
          chmod a+x test
          chmod a+x ./tests/run
          ./test
