name: CI
on:
  push:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly, v0.10.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}
      - name: Run Tests
        run: |
          nvim --version
          [ ! -d tests ] && exit 0
          chmod a+x test
          chmod a+x ./tests/run
          ./test
