name: Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Checkout wiki code
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: banana.nvim.wiki
      - name: Update wiki
        run: |
          mv banana.nvim.wiki/.git ./wikigit
          rm banana.nvim.wiki -rf
          cp wiki banana.nvim.wiki -r
          mv ./wikigit ./banana.nvim.wiki/.git
          cd ..
      - name: Push to wiki
        run: |
          cd banana.nvim.wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          MSG=$(git log -1 | tail -1)
          echo "$MSG"
          git diff-index --quiet HEAD || git commit -m "$MSG" && git push
          cd ..
      - name: Remove wiki
        run: |
          rm banana.nvim.wiki -rf
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}
      - name: Generate documentation
        run: |
          sudo wget https://github.com/jgm/pandoc/releases/download/3.6.1/pandoc-3.6.1-1-amd64.deb
          sudo dpkg -i pandoc-3.6.1-1-amd64.deb
          ./gendoc.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "doc"
          repository:
          commit_message: "chore(build): auto-generate docs"
