name: Docs
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  docs:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Update wiki
        run: |
          git clone https://github.com/CWood-sdf/banana.nvim.wiki
          mv banana.nvim.wiki/.git ./wikigit
          rm banana.nvim.wiki -rf
          cp wiki banana.nvim.wiki -r
          mv ./wikigit ./banana.nvim.wiki/.git
          MSG=$(git log -1 | tail -1)
          cd banana.nvim.wiki
          git status
          git config --global user.email "actions@github.com"
          git config --global user.name "Wiki mirror"
          git add .
          git commit -m "$MSG"
          git push
          cd ..
          rm banana.nvim.wiki -rf
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}
      - name: Generate documentation
        run: |
          sudo wget https://github.com/jgm/pandoc/releases/download/3.6.1/pandoc-3.6.1-1-amd64.deb
          sudo dpkg -i pandoc-3.6.1-1-amd64.deb
          ./gendoc.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "doc"
          repository:
          commit_message: "chore(build): auto-generate docs"
