name: Docs
on:
  gollum:
  workflow_dispatch:

jobs:
  docs:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rev: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}
      - name: Generate documentation
        run: |
          sudo wget https://github.com/jgm/pandoc/releases/download/3.6.1/pandoc-3.6.1-1-amd64.deb
          sudo dpkg -i pandoc-3.6.1-1-amd64.deb
          ./gendoc.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "doc"
          commit_message: "chore(build): auto-generate docs"
